Route12_MapScripts::
	.byte 0


Route12_BugManiac::
# 4 "data/maps/Route12/scripts.pory"
	trainerbattle_single TRAINER_ROUTE12_BUG_MANIAC, Route12_BugManiac_Text_0, Route12_BugManiac_Text_1
# 9 "data/maps/Route12/scripts.pory"
	msgbox Route12_BugManiac_Text_2, MSGBOX_AUTOCLOSE
	end


Route12_Hiker::
# 14 "data/maps/Route12/scripts.pory"
	trainerbattle_single TRAINER_ROUTE12_HIKER, Route12_Hiker_Text_0, Route12_Hiker_Text_1
# 19 "data/maps/Route12/scripts.pory"
	msgbox Route12_Hiker_Text_2, MSGBOX_AUTOCLOSE
	end


Route12_NinjaBoy::
# 24 "data/maps/Route12/scripts.pory"
	trainerbattle_single TRAINER_ROUTE12_NINJA_BOY, Route12_NinjaBoy_Text_0, Route12_NinjaBoy_Text_1
# 29 "data/maps/Route12/scripts.pory"
	msgbox Route12_NinjaBoy_Text_2, MSGBOX_AUTOCLOSE
	end


Route12_Breeder::
# 34 "data/maps/Route12/scripts.pory"
	trainerbattle_single TRAINER_ROUTE12_BREEDER, Route12_Breeder_Text_0, Route12_Breeder_Text_1
# 39 "data/maps/Route12/scripts.pory"
	msgbox Route12_Breeder_Text_2, MSGBOX_AUTOCLOSE
	end


Route12_BugManiac_Text_0:
# 6 "data/maps/Route12/scripts.pory"
	.string "Yo this tree wack!$"

Route12_BugManiac_Text_1:
# 7 "data/maps/Route12/scripts.pory"
	.string "Yo your team wack!$"

Route12_BugManiac_Text_2:
# 9 "data/maps/Route12/scripts.pory"
	.string "Yo why's this tree still green?$"

Route12_Hiker_Text_0:
# 16 "data/maps/Route12/scripts.pory"
	.string "Mountain climbing is a great time!$"

Route12_Hiker_Text_1:
# 17 "data/maps/Route12/scripts.pory"
	.string "Losing is not a great time...$"

Route12_Hiker_Text_2:
# 19 "data/maps/Route12/scripts.pory"
	.string "You need a bike to get up the slope?\nWeak.$"

Route12_NinjaBoy_Text_0:
# 26 "data/maps/Route12/scripts.pory"
	.string "AHA! Did I surprise you?$"

Route12_NinjaBoy_Text_1:
# 27 "data/maps/Route12/scripts.pory"
	.string "Aw shucks...$"

Route12_NinjaBoy_Text_2:
# 29 "data/maps/Route12/scripts.pory"
	.string "There's trees here, shouldn't my\n"
	.string "disguise blend in?$"

Route12_Breeder_Text_0:
# 36 "data/maps/Route12/scripts.pory"
	.string "Oh my!$"

Route12_Breeder_Text_1:
# 37 "data/maps/Route12/scripts.pory"
	.string "Aren't you a strong one?$"

Route12_Breeder_Text_2:
# 39 "data/maps/Route12/scripts.pory"
	.string "These little ones are going to need as\n"
	.string "much stamina as they can get.$"
