PortEdaph_Indoor2_MapScripts::
	.byte 0


PortEdaph_Indoor2_Man::
# 4 "data/maps/PortEdaph_Indoor2/scripts.pory"
	msgbox PortEdaph_Indoor2_Man_Text_0, MSGBOX_NPC
	return


PortEdaph_Indoor2_Woman::
# 8 "data/maps/PortEdaph_Indoor2/scripts.pory"
	msgbox PortEdaph_Indoor2_Woman_Text_0, MSGBOX_NPC
	return


PortEdaph_Indoor2_Man2::
# 12 "data/maps/PortEdaph_Indoor2/scripts.pory"
	msgbox PortEdaph_Indoor2_Man2_Text_0, MSGBOX_NPC
	return


PortEdaph_Indoor2_Kid::
# 16 "data/maps/PortEdaph_Indoor2/scripts.pory"
	msgbox PortEdaph_Indoor2_Kid_Text_0, MSGBOX_NPC
	return


PortEdaph_Indoor2_Man_Text_0:
# 4 "data/maps/PortEdaph_Indoor2/scripts.pory"
	.string "My brother is staying over at the\n"
	.string "moment, but I'm not sure if he's a great\l"
	.string "influence...$"

PortEdaph_Indoor2_Woman_Text_0:
# 8 "data/maps/PortEdaph_Indoor2/scripts.pory"
	.string "I'm glad my little boy is happy, but...$"

PortEdaph_Indoor2_Man2_Text_0:
# 12 "data/maps/PortEdaph_Indoor2/scripts.pory"
	.string "IF YOU WANNA PICK UP GIRLS THEN YOU\n"
	.string "GOTTA BE A MACHO MAN LIKE ME!$"

PortEdaph_Indoor2_Kid_Text_0:
# 16 "data/maps/PortEdaph_Indoor2/scripts.pory"
	.string "YEAH!$"
