LapashTown_Indoor1_MapScripts::
	.byte 0


LapashTown_Indoor1_OldWoman::
# 4 "data/maps/LapashTown_Indoor1/scripts.pory"
	msgbox LapashTown_Indoor1_OldWoman_Text_0, MSGBOX_NPC
	return


LapashTown_Indoor1_Boy::
# 8 "data/maps/LapashTown_Indoor1/scripts.pory"
	msgbox LapashTown_Indoor1_Boy_Text_0, MSGBOX_NPC
	return


LapashTown_Indoor1_Scientist::
# 12 "data/maps/LapashTown_Indoor1/scripts.pory"
	msgbox LapashTown_Indoor1_Scientist_Text_0, MSGBOX_NPC
	return


LapashTown_Indoor1_OldWoman_Text_0:
# 4 "data/maps/LapashTown_Indoor1/scripts.pory"
	.string "The ash collected here can be used to\n"
	.string "make incredible things, provided you\l"
	.string "have the skill.$"

LapashTown_Indoor1_Boy_Text_0:
# 8 "data/maps/LapashTown_Indoor1/scripts.pory"
	.string "I'm learning how to create special\n"
	.string "remedies using the ash found around\l"
	.string "here.$"

LapashTown_Indoor1_Scientist_Text_0:
# 12 "data/maps/LapashTown_Indoor1/scripts.pory"
	.string "Research into the properties of the\n"
	.string "ash here is arduous due to the\l"
	.string "difficulty of getting here from Libra\l"
	.string "Institute.$"
